var descriptions = [
   "<h1> Albania <h1> <h2> Gajde </h2> <img src=\"https://upload.wikimedia.org/wikipedia/commons/e/ef/Bag_piper%2C_Elbasan%2C_Albania.jpg\" style=\"width: 280px; height: 400px;\"> ",
   "<h1> Austria <h1> <h2> Bock </h2> <p> The drone of the Bock is usually pitched two octaves below the tonic of the chanter. The single drone and single chanter have cylindrical bores and employ single reeds. The current variant of the Bock is generally bellows-blown, which has the advantage of allowing the piper to sing along with their playing. The chanter and drone terminate in amplifying bells of horn or brass, angled upwards. The top end of the chanter is often shaped in the form of a goat-head. In Egerland-style instruments, the drone hangs downward from the bag, whereas in the Bohemian variant, the drone extends backwards over the player's shoulder.</p> <table> <tr> <td><figure><img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Bock_Dudelsack.jpg/579px-Bock_Dudelsack.jpg\" style=\"width: 309px; height: 480px;\"><figcaption>Bohemian-style Bock</figcaption></figure></td> <td><figure><img src=\"https://upload.wikimedia.org/wikipedia/commons/9/9c/Tomas_Spurny.jpg\" style=\"width: 281px; height: 480px;\"><figcaption>Egerland-style Bock</figcaption></figure></td></tr></table>",
   "<h1> Belarus <h1> <h2> Duda </h2> <img src=\"http://staryolsa.com/uploads/images/Gallery/instrumenty/en/duda-g-3/1H0A8412g.jpg\" style=\"width: 280px; height: 480px;\"> <p> The Duda consists of a bag, a blowpipe (soska) and a chanter (perabor) and it has one drone (gook). Both the chanter and the drone have a bell; each one curved. In the ancient Belarusian tradition, the Duda is an instrument for rites.</p>",
   "<h1> Belgium <h1>  <h2> Muchosa </h2> <img src=\"https://upload.wikimedia.org/wikipedia/commons/2/27/Muchosac.JPG\" style=\"width: 640px; height: 480px;\"> <p>The muchosa is a type of bagpipe found in the French-speaking part of Belgium and northern France, where it is known as the pipasso.The muchosa has a chanter with a conical bore and double reed, pitched to B-flat. It has two single-reed drones. The treble drone is placed in a common stock with the chanter, and the bass drone is placed further back in its own stock. </p> <br> <p>The doedelzak is another type of bagpipes found in Dutch-speaking Belgium and The Netherlands (for more information, see <em>The Netherlands</em>).<p>",
   "<h1> Bulgaria <h1> <h2> Kaba gaida </h2> <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/BulgarianKabaGaidaPlayer.jpg/603px-BulgarianKabaGaidaPlayer.jpg\" style=\"width: 322px; height: 480px;\"> <p> The kaba gaida (the Rhodope Mountains bagpipe) is one of the most distinctive symbols of the folklore music in Bulgaria. The chanter has a specific curve at the end and has hexagonal profile. Usually the bag is larger. The shape of the channel inside the chanter is reverse cone. The most common drone tone on a kaba gaida is E.</p>",
   "<h1> Croatia <h1> <h2> Istarski mih </h2> <table><tr><td><img src=\"http://kulturistra.hr/wp-content/uploads/2009/10/Mih-u-Groz%cc%8cnjanu-by-Aldo-S%cc%8curan.JPG\" style=\"width: 270px; height: 189px;\"></td><td><img src=\"http://www.gajde.com/wp-content/uploads/2012/11/istarski-mih-300x201.png\" style=\"width: 300px; height: 240px;\"></td></tr></table> <p> This type of bagpipe is distinct in that it has no drones, but a double-chanter with finger-holes on both bores, allowing both a melody and changing harmony to be played. The double chanter is usually cut from a single rectangular piece of wood.</p>",
   "<h1> Estonia <h1>  <h2> Torupill </h2> <img src=\"http://www.mulgimaa.ee/userfiles/ants_taul.jpg\" style=\"width: 480px; height: 350px;\"> <p> The Estonian bagpipe has a bag, a mouth-pipe (blow-pipe) for inflating the bag, a melody-pipe (chanter) and 1 or 2, rarely 3, drones. The chanter is single-reeded, generally with a parallel rather than conical bore.</p>",
   "<h1> France <h1> <h2> Musette de cour </h2> <table><tr><td><img src=\"https://upload.wikimedia.org/wikipedia/commons/6/67/Gueidan.jpg\" style=\"width: 240px; height: 300px;\"></td><td><img src=\"http://www.els-salancaires.fr/historiques/infos%20historique%20sac/musette%20de%20cour.jpg\" style=\"width: 270px; height: 189px;\"></td><td><img src=\"https://vichyencheres.files.wordpress.com/2011/03/ve-2011-06-musette-de-cour-19.jpg\" style=\"width: 189px; height: 300px;\"></td></tr></table> <p> France has several types of bagpipes, one of them being the musette de cour. The musette de cour or baroque musette is characterised by the short, cylindrical shuttle-drone and the two chanters. Both the chanters and the drones have a cylindrical bore and use a double reed, giving a quiet tone similar to the oboe. The instrument is blown by a bellows. The qualification de cour refers to the instrument's connection with the French court and aristocracy of the early seventeenth century. </p>",
   "<h1> Georgia <h1> <h2> Gudastviri </h2> <img src=\"https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.hangebi.ge%2Fimages%2Fgallery-instruments%2Fguda-maizer2-wide.jpg&f=1\" style=\"width: 320px; height: 350px;\"> <p> The gudastviri is made up of two main parts: The first being a whole sheep or goat skin, or a sewed, rectangular leather bag. The second is a yoked double-chanter, terminating in a single horn bell. There is a small wooden blow-pipe with a check-valve tied into one leg or corner of the bag. A fixed round wooden stock holding the chanter is tied into the bag in the opposite foreleg or corner. The chanter itself has two wooden pipes of equal length, bore and wall thickness, which are inserted into the stock. The instrument has no drones.</p>",
   "<h1> Germany <h1> <h2> Marktsackpfeife </h2> <img src=\"http://www.melbar.eu/items/Musikinstrumente/Sackpfeifen/Sackpfeifen-Mittelalter-Markt-Dudelsack-MM2410212200.jpg\" style=\"width: 350px; height: 350px;\"> <p> The Marktsackpfeife is a visual reconstruction of medieval bagpipes. However, while the exterior is reconstructed from these sources, the interior has its own distinct, modern characteristics, creating a modern bagpipe with no historical counterparts. The instruments has one to three drones. </p>",
   "<h1> Greece <h1> <h2> Tsampouna </h2> <img src=\"http://3.bp.blogspot.com/-zA8JH2ET2Fw/UMFIttQlPQI/AAAAAAAAFY4/_3Xf--Hpuok/s1600/Tsambouna,+Tsampouna+01.jpg\" style=\"width: 250px; height: 350px;\"> <p> The tsampouna is a double-chantered bagpipe, with no drone and is inflated by blowing by mouth into a goatskin bag.</p>",
   "<h1> Hungary <h1> <h2> Magyar Duda </h2> <table> <tr> <td><figure><img src=\"http://www.irodalmiradio.hu/femis/zene/hgszene/4levego/13paloc_duda.jpg\" style=\"width: 400px; height: 250px;\"><figcaption></figcaption></figure></td> <td><figure><img src=\"https://upload.wikimedia.org/wikipedia/commons/c/cc/Duda_Bagpipe_001.jpg\" style=\"width: 244px; height: 480px;\"><figcaption>Chanter of the Magyar Duda</figcaption></figure></td></tr></table><p> The most characteristic feature of the magyar duda is the double-bored chanter. One chanter bore, the melody pipe, plays the melody within an octave range. The second chanter, the contra pipe, has a single finger hole and sounds either the lowest note on the melody pipe or drops to the dominant (i.e., on a pipe in A it sounds either A or E). There is considerable variation in physical appearance of the duda in Hungary, but the most common form has a chanter stock in the form of an animal’s head (usually that of a goat-like animal) and a cow horn bell on both the chanter and the drone.</p>",
   "<h1> Ireland <h1> <h2> Uilleann Pipes </h2> <table><tr><td><img src=\"http://www.trocmusic.com/images/annonces/231943.jpg\" style=\"width: 250px; height: 189px;\"></td><td><img src=\"https://upload.wikimedia.org/wikipedia/commons/4/48/Cillian_Vallely_on_Uilleann_Pipes.jpg\" style=\"width: 191px; height: 240px;\"></td></tr></table> <p> The uilleann pipes are the characteristic national bagpipe of Ireland. The bag of the uilleann pipes is inflated by means of a small set of bellows strapped around the waist and the arm. The uilleann pipes are distinguished from many other forms of bagpipes by their tone and wide range of notes – the chanter has a range of two full octaves, including sharps and flats – together with the unique blend of chanter, drones, and regulators. The regulators are equipped with closed keys that can be opened by the piper's wrist action enabling the piper to play simple chords, giving a rhythmic and harmonic accompaniment as needed. There are also many ornaments based on multiple or single grace notes. The chanter can also be played staccato by resting the bottom of the chanter on the piper's thigh to close off the bottom hole and then open and close only the tone holes required. If one tone hole is closed before the next one is opened, a staccato effect can be created because the sound stops completely when no air can escape at all. The uilleann pipes are often played indoors, and are almost always played sitting down.</p>",
   "<h1> Italy <h1> <h2> Zampogna </h2> <img src=\"https://i.ytimg.com/vi/3pa4W7iA5So/maxresdefault.jpg\" style=\"width: 480px; height: 300px;\"> <p> All chanters and drones are fixed into a single round stock that the bag is attached to. Each chanter is tuned differently, according to the tradition it represents, and there are dozens. Typically, the double-reeded versions will have a soprano chanter on the right and a bass chanter on the left with an alto drone; but as many as three drones, the other tuned above and below the basic chord can be used, or no drones at all.</p>",
   "<h1> F.Y.R. Macedonia <h1> <h2> Gaida </h2> <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Gaida.jpg/386px-Gaida.jpg\" style=\"width: 309px; height: 480px;\"> <p> The Macedonian gaida is similar to other bagpipes found in Balkan countries. The gaida has a single chanter pipe and one drone pipe. The reeds are single (like a clarinet reed). The gaida can be played unaccompanied, but percussion instruments are played when another musician is available. The favorite accompaniment for the gaida varies. In Macedonia and Aegean Macedonia the tupun (large drum) accompanies the gaida. Also, the defi or daires (small hand drum like a tambourine) accompanies the gaida.</p>",
   "<h1> Malta <h1> <h2> Żaqq </h2> <img src=\"http://4.bp.blogspot.com/-mnraaEQq2-0/Uq4ISPtfElI/AAAAAAAAJ9w/fYtJIRvDjFQ/s640/Iz-Zaqq+01+(Malta).jpg\" style=\"width: 300px; height: 400px;\"> <p>A double-chantered, single-reed, droneless hornpipe.</p>",
   "<h1> The Netherlands <h1> <h2> Doedelzak </h2> <img src=\"http://www.banchetto-musicale.de/images/flame.jpg\" style=\"width: 322px; height: 480px;\"> <p> Also called <em>pijpzak</em> or <em>moezelzak</em>. In English this type of bagpipe is usually referred to as the <em>Flemish bagpipe</em>. It is a two-droned bagpipe. The instrument is held rather in front of the player than under the arm. The two drone pipes, which have single reeds and are typically a fifth apart, are in the same stock and face directly up or slightly forward, depending on the individual position of the piper. The chanter has a conical pierce and a double reed.</p> <br> <p>Click on this country to find out more about this bagpipe.</p>",
   "<h1> Poland <h1> <h2> Kozioł </h2> <img src=\"http://blog.instrumenty.edu.pl/wp-content/uploads/2015/09/img_8212.jpg\" style=\"width: 480px; height: 350px;\"> <p> The kozioł features a drone with a projecting horn, and is inflated with bellows rather than the mouth. The name (literally: white goat) comes from the use of a hair-out goat's hide for the pipebag, and this is often complemented by a carved wooden goat's head ornamenting the stock of the chanter.</p>",
   "<h1> Portugal <h1> <h2> Gaita de foles mirandesa </h2> <img src=\"http://www.gaitadefoles.net/gaitadefoles/transmontana500.jpg\" style=\"width: 480px; height: 300px;\"> <p> This type of bagpipe features a single drone and a double-reed chanter.</p>",
   "<h1> Romania <h1> <h2> Cimpoi </h2> <img src=\"https://upload.wikimedia.org/wikipedia/commons/a/a6/Cimpoi_romanesc_1.jpg\" style=\"width: 232px; height: 201px;\"> <p> The cimpoi has a straight bore chanter with five to eight finger holes, and is sometimes curved at the end. There are two types of cimpoi, one with a single drone and one with two. The bag is made of a whole lamb or goat skin and, depending on the region, is made either with the fur in or out. It is sometimes covered with embroidered cloth. Also found in Moldova. </p>",
   "<h1> Russia <h1> <h2> Volynka </h2> <img src=\"http://txominagirreikastola.wikispaces.com/file/view/Volynka.jpg/254527874/Volynka.jpg\" style=\"width: 400px; height: 350px;\"> <p>The volynka is constructed around a goat skin air reservoir into which air is blown through a pipe with a valve to stop air escaping. A number of playing pipes [two to four] extend from the reservoir holding the air. The chanter has five to seven, sometimes eight finger holes. The other pipes produce a drone. Each of these playing pipes has a double reed usually made from a goose quill. This bagpipe is very similar to the Finnish Pilai.</p>",
   "<h1> Serbia <h1> <h2> Gajde </h2> <img src=\"https://upload.wikimedia.org/wikipedia/commons/0/01/Serbian_bagpiper.jpg\" style=\"width: 209px; height: 480px;\"> <p> The Serbian gajde features a single drone. A distinctive feature of the gajde's chanter (which it shares with a number of other Eastern European bagpipes) is the flea-hole (also known as a mumbler or voicer, marmorka) which is covered by the index finger of the left hand. The flea-hole is smaller than the rest and usually consists of a small tube that is made out of metal or a chicken or duck feather. Uncovering the flea-hole raises any note played by a half step, and it is used in creating the musical ornamentation that gives Balkan music its unique character. The chanter also has a double bored chanter. It has eight fingerholes: the top four are covered by the thumb and the first three fingers of the left hand, then the four fingers of the right hand cover the remaining four holes.</p>",
   "<h1> Spain <h1> <h2> Xeremia </h2> <img src=\"https://upload.wikimedia.org/wikipedia/commons/7/7c/Xeremier.jpg\" style=\"width: 300px; height: 480px;\"> <p> The xeremia is a type of bagpipe native to the island of Majorca (Mallorca). It consists of a bag made of skin (or modern synthetic materials), which retains the air, a blowpipe, a melody pipe or chanter, and several, generally three, drones. The primary drone sounds a tonic note, but the other drones are sometimes simply false drones for ornamentation. The xeremia has a distinctively bright and piercing sound, which has traditionally accompanied festivals and other activities in the islands throughout history.</p>",
   "<h1> Sweden <h1> <h2> Säckpipa </h2> <img src=\"http://www.albanfaust.se/uploads/pics/sackpipa_2_gal.jpg\" style=\"width: 400px; height: 300px;\"> <p> This type of bagpipe is notably smaller than other types of bagpipes and has a single drone and a single-reed chanter. The tone of the instrument is quite soft, not too different from that of a harmonica or an accordion.</p>",
   "<h1> Turkey <h1> <h2> Tulum </h2> <img src=\"http://www.bigloveturkey.com/culture/img/thm_instrumnets_tulum1.jpg\" style=\"width: 380px; height: 300px;\"> <p> The tulum is droneless with two parallel chanters.</p>",
   "<h1> England <h1> <h2> Northumbrian smallpipes </h2> <table> <tr> <td><img src=\"http://www.cheviotschallenge.org.uk/Images/northumbrian_pipes.jpg\" style=\"width: 400px; height: 340px;\"></td> <td><figure><img src=\"http://www.borderbagpipes.com/img/products/chanter1.JPG\" style=\"width: 50px; height: 400px;\"><figcaption>Keyed chanter of the Northumbrian smallpipes</figcaption></figure></td></tr></table> <p> The Northumbrian smallpipes are bellows-blown bagpipes from Northeastern England, particularly Northumberland. The instrument consists of one chanter and usually four drones. The cylindrically-bored chanter has a number of metal keys, most commonly seven, but chanters with a range of over two octaves can be made which require seventeen or more keys, all played with either the right hand thumb or left little finger. The Northumbrian smallpipes' chanter having a completely closed end, combined with the unusually tight fingering style (each note is played by lifting only one finger or opening one key) means that traditional Northumbrian piping is staccato in style. Because the bores are so narrow, (typically about 4.3 millimetres for the chanter), the sound is far quieter than most other bagpipes. </p>",
   "<h1> Scotland <h1> <h2> Great Highland bagpipe </h2> <img src=\"http://www.scotlandproductsonline.com/5-181-thickbox/ebony-african-blackwood-great-highland-bagpipe.jpg\" style=\"width: 480px; height: 480px;\"> <p> This is perhaps the world's best-known bagpipe. The Great Highland bagpipe has four reeds: the chanter reed (double), two tenor drone reeds (single), and one bass drone reed (single). A modern bagpipe has a bag, a chanter, a blowpipe, two tenor drones, and one bass drone. The two tenor drones are generally an octave below the keynote of the chanter (low A), and the bass drone two octaves below.</p>",
   "<h1> Wales <h1> <h2> Pibau Cymreig </h2> <p> Today there are two types of bagpipe made and played in Wales. One species uses a single-reed in the chanter, and the other uses a double-reed. The single-reed chanter is also furnished with a cow-horn bell. Both types of chanter may also be played un-attached to the bag; the single-reed type in the form of a hornpipe (Welsh: pibgorn), and the double-reed type in the form of a shawm. </p> <table> <tr> <td><figure><img src=\"https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.welshbagpipes.co.uk%2Fresources%2F_wsb_194x251_Ceri%2BRhys%2BMatthews.jpg&f=1\" style=\"width: 200px; height: 250px;\"><figcaption>Single-reed type Welsh bagpipe</figcaption></figure></td> <td><figure><img src=\"http://www.welshbagpipes.co.uk/resources/_wsb_289x432_Antwn.JPG\" style=\"width: 200px; height: 300px;\"><figcaption>Double-reed type Welsh bagpipe</figcaption></figure></td></tr><tr> <td><figure><img src=\"https://upload.wikimedia.org/wikipedia/commons/7/7c/Welshpibgorn.jpg\" style=\"width: 200px; height: 180px;\"><figcaption>Pibgorn</figcaption></figure></td> <td><figure><img src=\"https://i.pinimg.com/736x/a1/bc/7c/a1bc7c1cb6a92c155450ca7be6e53f99.jpg\" style=\"width: 200px; height: 250px;\"><figcaption>Shawm</figcaption></figure></td></tr></table>"
];

var songs = [];
var current_song = -1;

function preload(){
    songs[0] = loadSound("music/Albania.mp3");
    songs[1] = loadSound("music/Austria.mp3");
    songs[2] = loadSound("music/Belarus.mp3");
    songs[3] = loadSound("music/Belgium.mp3");
    songs[4] = loadSound("music/Bulgaria.mp3");
    songs[5] = loadSound("music/Croatia.mp3");
    songs[6] = loadSound("music/Estonia.mp3");
    songs[7] = loadSound("music/France.mp3");
    songs[8] = loadSound("music/Georgia.mp3");
    songs[9] = loadSound("music/Germany.mp3");
    songs[10] = loadSound("music/Greece.mp3");
    songs[11] = loadSound("music/Hungary.mp3");
    songs[12] = loadSound("music/Ireland.mp3");
    songs[13] = loadSound("music/Italy.mp3");
    songs[14] = loadSound("music/Macedonia.mp3");
    songs[15] = loadSound("music/Malta.mp3");
    songs[16] = loadSound("music/The Netherlands.mp3");
    songs[17] = loadSound("music/Poland.mp3");
    songs[18] = loadSound("music/Portugal.mp3");
    songs[19] = loadSound("music/Romania.mp3");
    songs[20] = loadSound("music/Russia.mp3");
    songs[21] = loadSound("music/Serbia.mp3");
    songs[22] = loadSound("music/Spain.mp3");
    songs[23] = loadSound("music/Sweden.mp3");
    songs[24] = loadSound("music/Turkey.mp3");
    songs[25] = loadSound("music/England.mp3");
    songs[26] = loadSound("music/Scotland.mp3");
    songs[27] = loadSound("music/Wales.mp3");
    
    select("#soundoff").hide();
    select("#soundon").hide();
}

function displayInfoB(i) {
    var div = document.getElementById("description");
    div.innerHTML = descriptions[i];
    if (current_song != i) {
        if (current_song >= 0) songs[current_song].stop();
        songs[i].loop();
        current_song = i;
    }
}

function toggleMusic(i) {
    if (i) {
        // turn sound off
        select("#soundon").hide();
        select("#soundoff").show();
        masterVolume(0.0);
    } else {
        // turn sound on
        select("#soundoff").hide();
        select("#soundon").show();
        masterVolume(1.0);
    }
}

function setup() {
    createCanvas(0, 0);
    select("#soundon").show();
}
